### PR TITLE
Added Steps support

### PR DESCRIPTION
**Pull request by dusty73**
## what
* Added the property "step" that allow specifying steps to run after EMR cluster startup

## why
* Steps are in some cases needed for further configuring EMR cluster once it's started

### CODE REVIEW

**Comment by aknysh** [comment]
@dusty73 please rebase

**Comment by dusty73** [comment]
> @dusty73 please rebase

Sorry for the silly/obvious question, how do I rebase?

> @dusty73 please rebase

Sorry for the silly/obvious question, how do I rebase?

**Comment by dusty73** [comment]
Resubmitting the PR rebased and updated

**Pull request closed without merging**
