### PR TITLE
Fix `log_uri` in example

### PR DESCRIPTION
**Pull request by yujunz**
Closes: #8

### CODE REVIEW

**Comment by yujunz** [comment]
`make && make readme` seems failing. `README.md` updated manually.

**Comment by aknysh** [comment]
thanks @yujunz 

did you run 
```
make init
make readme/deps
make readme
```

which part of this is failing?
what OS are you using?

**Comment by yujunz** [comment]
It seems `terraform-docs` is outdated for terraform 0.12, under macOS Catalina.

```
❯ make init
Removing existing build-harness
Cloning https://github.com/cloudposse/build-harness.git#master...
Cloning into 'build-harness'...
remote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 1303 (delta 42), reused 79 (delta 38), pack-reused 1216
Receiving objects: 100% (1303/1303), 274.81 KiB | 316.00 KiB/s, done.
Resolving deltas: 100% (651/651), done.

❯ make readme/deps
Installing packages 0.95.0...
Cloning into '/Users/yujunz/Code/github.com/cloudposse/terraform-aws-emr-cluster/build-harness/vendor/packages'...
remote: Enumerating objects: 293, done.
remote: Counting objects: 100% (293/293), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 293 (delta 52), reused 246 (delta 43), pack-reused 0
Receiving objects: 100% (293/293), 52.59 KiB | 1.05 MiB/s, done.
Resolving deltas: 100% (52/52), done.
curl --retry 3 --retry-delay 5 --fail -sSL -o /Users/yujunz/Code/github.com/cloudposse/terraform-aws-emr-cluster/build-harness/vendor/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v3.1.0/gomplate_darwin-amd64-slim && chmod +x /Users/yujunz/Code/github.com/cloudposse/terraform-aws-emr-cluster/build-harness/vendor/gomplate

❯ make readme
curl --retry 3 --retry-delay 5 --fail -sSL -o /Users/yujunz/Code/github.com/cloudposse/terraform-aws-emr-cluster/build-harness/vendor/terraform-docs https://github.com/segmentio/terraform-docs/releases/download/v0.4.5/terraform-docs-v0.4.5-darwin-amd64 && chmod +x /Users/yujunz/Code/github.com/cloudposse/terraform-aws-emr-cluster/build-harness/vendor/terraform-docs
2019/10/24 11:33:10 At 3:16: Unknown token: 3:16 IDENT var.enabled
make: *** [docs/terraform.md] Error 1
```

**Pull request merged**
